# DROP TABLE

drop_orders_table = 'DROP TABLE IF EXISTS orders'

# CREATE TABLE

create_orders_table = '''
CREATE TABLE IF NOT EXISTS orders
(
ORDERNUMBER INT PRIMARY KEY,
QUANTITYORDERED	INT,
PRICEEACH DECIMAL,
ORDERLINENUMBER	INT,
SALES DECIMAL,
ORDERDATE DATE,
STATUS VARCHAR(50),
QTR_ID INT,
MONTH_ID INT,
YEAR_ID INT,
PRODUCTLINE VARCHAR(50),
MSRP INT,
PRODUCTCODE	VARCHAR(50),
CUSTOMERNAME VARCHAR(50),
PHONE VARCHAR(50),
ADDRESSLINE1 VARCHAR(50),
ADDRESSLINE2 VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTALCODE VARCHAR(50),
COUNTRY VARCHAR(50),
TERRITORY VARCHAR(50),
CONTACTLASTNAME VARCHAR(50),
CONTACTFIRSTNAME VARCHAR(50),
DEALSIZE VARCHAR(50)
)
'''

# INSERT INTO

insert_orders_table = '''
    INSERT INTO orders
    (ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES,
    ORDERDATE, STATUS, QTR_ID, MONTH_ID, YEAR_ID, 
    PRODUCTLINE, MSRP, PRODUCTCODE, CUSTOMERNAME, PHONE, 
    ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, 
    COUNTRY, TERRITORY, CONTACTLASTNAME, CONTACTFIRSTNAME, DEALSIZE)

    VALUES (%s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, 
            %s, %s, %s, %s, %s)
    '''